CREATE TABLE `customer` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`Segment` VARCHAR(20) NOT NULL DEFAULT '0',
	`SCN` INT(11) NOT NULL DEFAULT '0',
	`IntegrationID` INT(11) NOT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE INDEX `Integration` (`IntegrationID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=140351
;


CREATE TABLE `individual` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(50) NOT NULL,
	`SURNAME` VARCHAR(50) NOT NULL,
	`SCN` INT(11) NOT NULL,
	`IntegrationID` INT(11) NOT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE INDEX `Integration` (`IntegrationID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=140363
;


CREATE TABLE `partyrole` (
	`CustID` INT(11) NOT NULL,
	`IndID` INT(11) NOT NULL,
	PRIMARY KEY (`CustID`, `IndID`),
	INDEX `FK_Ind` (`IndID`),
	CONSTRAINT `FK_Cust` FOREIGN KEY (`CustID`) REFERENCES `customer` (`ID`),
	CONSTRAINT `FK_Ind` FOREIGN KEY (`IndID`) REFERENCES `individual` (`ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;



CREATE TABLE `address` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`Gaia` INT(11) NOT NULL DEFAULT '0',
	`Street` VARCHAR(60) NOT NULL DEFAULT '0',
	`Number` VARCHAR(5) NOT NULL DEFAULT '0',
	`City` VARCHAR(20) NOT NULL DEFAULT '0',
	`PostalCode` VARCHAR(6) NOT NULL DEFAULT '0',
	`IntegrationID` INT(11) NOT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE INDEX `Integration` (`IntegrationID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=272
;


CREATE TABLE `contactmedium` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`EMAIL` VARCHAR(40) NULL DEFAULT NULL,
	`PHONE` VARCHAR(20) NULL DEFAULT NULL,
	`ADDRID` INT(11) NULL DEFAULT NULL,
	`TYPE` TINYTEXT NOT NULL DEFAULT '0',
	`IND_ID` INT(11) NOT NULL DEFAULT '0',
	`IntegrationID` INT(11) NOT NULL,
	PRIMARY KEY (`ID`),
	UNIQUE INDEX `MEDIUMS_IND` (`IND_ID`, `TYPE`(100)),
	INDEX `Addr_FK` (`ADDRID`),
	INDEX `‌Integration` (`IntegrationID`),
	CONSTRAINT `Addr_FP` FOREIGN KEY (`ADDRID`) REFERENCES `address` (`ID`),
	CONSTRAINT `IND_ID_FK` FOREIGN KEY (`IND_ID`) REFERENCES `individual` (`ID`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
AUTO_INCREMENT=420897
;


