{
 "title": "Migracion",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Total Records Processed",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(NumberOfRecords{Status=\"Processed\",exported_job=~\"individual.*\"})",
     "legendFormat": "Total Records Processed"
    }
   ]
  },
  {
   "title": "Processed per min",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(NumberOfRecords{Status=\"Processed\",exported_job=~\"individual.*\"}[1m]))",
     "legendFormat": "Records per min"
    }
   ]
  },
  {
   "title": "Speed per Unit of Work (in secs)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(Elapsed_sum{exported_job=~\"individual.*\"}[30s]))/sum(rate(Elapsed_count{exported_job=~\"individual.*\"}[30s]))/1000",
     "legendFormat": "Elapsed per UW"
    }
   ]
  },
  {
   "title": "Speed per Record (in secs)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(Elapsed_sum{exported_job=~\"individual.*\"}[30s]))/sum(rate(Elapsed_count{exported_job=~\"individual.*\"}[30s]))/1000/sum(rate(NumberOfRecords{Status=\"Processed\",exported_job=~\"individual.*\"}[30s]))",
     "legendFormat": "Elapsed per record"
    }
   ]
  },
  {
   "title": "Total Records in Error",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(NumberOfRecords{Status=\"Error\",exported_job=~\"individual.*\"})"
    }
   ]
  },
  {
   "title": "Errors per min",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(NumberOfRecords{Status=\"Error\",exported_job=~\"individual.*\"}[1m]))",
     "legendFormat": "Errors per min"
    }
   ]
  },
  {
   "title": "Records per Unit of Work",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(NumberOfRecordsWU_sum{exported_job=~\"individual.*\"}[5m]))/sum(rate(NumberOfRecordsWU_count{exported_job=~\"individual.*\"}[5m]))"
    }
   ]
  },
  {
   "title": "# Process running",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(NumberOfProcesses{exported_job=~\"individual.*\"})",
     "legendFormat": "# Process running"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_threads_current{exported_job=~\"individual.*\"})",
     "legendFormat": "Current"
    },
    {
     "expr": "sum(jvm_threads_deadlocked{exported_job=~\"individual.*\"})  ",
     "legendFormat": "Deadlocked"
    },
    {
     "expr": "sum(jvm_threads_peak{exported_job=~\"individual.*\"})  ",
     "legendFormat": "Peak"
    }
   ]
  },
  {
   "title": "CPU seconds per min",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(process_cpu_seconds_total{exported_job=~\"individual.*\"}[1m]))",
     "legendFormat": "CPU seconds per min"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_bytes_init{exported_job=~\"individual.*\"}) /1024/1024",
     "legendFormat": "Bytes Used (MB) {{area}}"
    },
    {}
   ]
  }
 ]
}